on: push

name: Sample Workflow

jobs:
  build:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - run: flutter pub get
        
      - name: generate floor
      - run: flutter packages pub run build_runner build
  
      - name: Analyze Flutter
        uses: zgosalvez/github-actions-analyze-flutter@v1
